// examples/voice-search/app.tsx
/** @jsxRuntime classic */
/** @jsx h */
import { autocomplete, getAlgoliaResults } from '@kumoai/autocomplete-js';
import { Hit } from '@algolia/client-search';
import algoliasearch from 'algoliasearch/lite';
import { h } from 'preact';

import '@kumoai/autocomplete-theme-classic';
import { createVoiceSearchPlugin } from './voiceSearchPlugin';

const appId = 'latency';
const apiKey = '6be0576ff61c053d5f9a3225e2a90f76';
const searchClient = algoliasearch(appId, apiKey);

type AutocompleteItem = Hit<{
  brand: string;
  categories: string[];
  description: string;
  image: string;
  name: string;
  price: number;
  rating: number;
  type: string;
  url: string;
}>;

const voiceSearchPlugin = createVoiceSearchPlugin({});

autocomplete<AutocompleteItem>({
  container: '#autocomplete',
  placeholder: 'Search',
  detachedMediaQuery: 'none',
  insights: true,
  plugins: [voiceSearchPlugin],
  getSources({ query }) {
    return [
      {
        sourceId: 'products',
        getItems() {
          return getAlgoliaResults<AutocompleteItem>({
            searchClient,
            queries: [
              {
                indexName: 'instant_search',
                query,
              },
            ],
          });
        },
        templates: {
          item({ item, components }) {
            return (
              <div className="aa-ItemWrapper">
                <div className="aa-ItemContent">
                  <div className="aa-ItemIcon aa-ItemIcon--picture aa-ItemIcon--alignTop">
                    <img
                      src={item.image}
                      alt={item.name}
                      width="40"
                      height="40"
                    />
                  </div>

                  <div className="aa-ItemContentBody">
                    <div className="aa-ItemContentTitle">
                      <components.Highlight hit={item} attribute="name" />
                    </div>
                    <div className="aa-ItemContentDescription">
                      By <strong>{item.brand}</strong> in{' '}
                      <strong>{item.categories[0]}</strong>
                    </div>
                  </div>
                </div>
              </div>
            );
          },
          noResults() {
            return 'No products matching.';
          },
        },
      },
    ];
  },
});

// examples/vue/src/App.vue
<template>
  <div class="container">
    <div id="autocomplete" />
  </div>
</template>

<script lang="jsx">
import { h, Fragment, render, onMounted } from 'vue';
import { autocomplete, getAlgoliaResults } from '@kumoai/autocomplete-js';
import algoliasearch from 'algoliasearch/lite';

import '@kumoai/autocomplete-theme-classic';

import { createElement } from './utils/createElement';
import ProductItem from './components/ProductItem.vue';

const appId = 'latency';
const apiKey = '6be0576ff61c053d5f9a3225e2a90f76';
const searchClient = algoliasearch(appId, apiKey);

export default {
  name: 'App',
  setup() {
    onMounted(() => {
      autocomplete({
        container: '#autocomplete',
        placeholder: 'Search',
        insights: true,
        getSources({ query }) {
          return [
            {
              sourceId: 'products',
              getItems() {
                return getAlgoliaResults({
                  searchClient,
                  queries: [
                    {
                      indexName: 'instant_search',
                      query,
                    },
                  ],
                });
              },
              templates: {
                item({ item, components }) {
                  return (
                    <ProductItem item={item} highlight={components.Highlight} />
                  );
                },
              },
            },
          ];
        },
        renderer: {
          createElement,
          Fragment,
          render,
        },
      });
    });
  },
};
</script>

<style>
.container {
  margin: 0 auto;
  max-width: 640px;
  width: 100%;
}
</style>
